---
- name: "set npm jobs config"
  command: bash -lc "npm config set jobs {{ npm_config_jobs }}"
  remote_user: "{{ deployer }}"
  args:
    chdir: "{{ project_path }}/{{ frontend_dir }}"


- when: npm_config_install_production == True
  name: calculate npm install options
  set_fact: npm_install_options="--production"


- name: "fetch npm dependencies"
  command: bash -lc "cd {{ project_path }}/{{ frontend_dir }} && npm install {{npm_install_options}}"
  remote_user: "{{ deployer }}"
  async: 1800
  debugger: on_failed
  tags: "npm-deps"

- name: "build frontend assets"
  command: bash -lc "{{ frontend_build_command }}"
  remote_user: "{{ deployer }}"
  args:
    chdir: "{{ project_path }}/{{ frontend_dir }}"
  tags: "build-brunch"  

- when: "post_frontend_build != False"
  name: "post-frontend-build command"
  command: 'bash -lc "{{ post_frontend_build }}"'
  remote_user: "{{ deployer }}"
  args:
    chdir: "{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
