- when: "database_name is not defined"
  name: "calculate database name"
  set_fact: "database_name={{ app_name }}_prod"

- name: "create or get mysql password"
  set_fact: database_password="{{ lookup('password', '~/credentials/' + deployer + '_postgres length=15') }}"

- name: "set database user"
  set_fact: database_user="{{ deployer }}"