- when: "database_name is not defined"
  name: "calculate database name"
  set_fact: "database_name={{ app_name }}_prod"

- name: "create or get mysql password"
  set_fact: database_password="{{mysql_root_db_pass}}"

- name: "set database user"
  set_fact: database_user="root"