---
- name: Add wkhtmltopdf specific variables
  include_vars: "wkhtmltopdf.yml"

- name: "Ensure dependencies are installed"
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - libqt5core5a
    - fontconfig
    - libfontconfig1
    - libfreetype6
    - libpng12-0
    - libxrender1
    - xfonts-base
    - xfonts-75dpi
    - wkhtmltopdf
  tags:
    - wkhtmltopdf
    - pkgs
